server:
  port: 8888

spring:
  application:
    name: service-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    gateway:
      discovery:
        locator:
          enabled: true

      routes:
      - id: service-edu
        uri: lb://service-edu
        predicates:
        - Path=/edu/service/**

      - id: service-center
        uri: lb://service-center
        predicates:
        - Path=/center/member/**
