# 服务端口
server:
  port: 8002

# 服务名
spring:
  application:
    name: service-oss
  # 环境设置
  profiles:
    active: dev
  # nacos的配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
