# 服务端口
server:
  port: 8003

# 服务名
spring:
  application:
    name: service-vod
  # 环境设置
  profiles:
    active: dev
  # nacos的配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  # 最大单个文件上传大小
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
